version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
    - '4369:4369'
    - '5672:5672'
    - '25672:25672'
    - '15672:15672'
    volumes:
    - 'rabbitmq_data:/bitnami'
    environment:
    - RABBITMQ_USERNAME=rabbitmq
    - RABBITMQ_PASSWORD=rabbitmq
    networks:
    - docker-network-local

  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
    - '5432:5432'
    volumes:
    - 'postgres_data:/bitnami'
    environment:
    - POSTGRESQL_PASSWORD=postgresx
    networks:
    - docker-network-local

  redis:
    image: 'redis:4.0-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/redis'
    networks:
      - docker-network-local

volumes:
  rabbitmq_data:
    driver: local

  postgres_data:
    driver: local

  redis_data:
    driver: local

networks:
  docker-network-local:
